# Copyright (c) Streamlit Inc. (2018-2022) Snowflake Inc. (2022-2025)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
다국어 설정 모듈
한국어, 영어, 일본어 번역 텍스트를 관리합니다.
"""

from typing import Dict

DEFAULT_LANG = "ko"

LANG: Dict[str, Dict[str, str]] = {
    "ko": {
        "title": "개인 맞춤형 AI 학습 코치 (음성 및 DB 통합)",
        "sidebar_title": "📚 AI Study Coach 설정",
        "file_uploader": "학습 자료 업로드 (PDF, TXT, HTML)",
        "button_start_analysis": "자료 분석 시작 (RAG Indexing)",
        "rag_tab": "RAG 지식 챗봇",
        "content_tab": "맞춤형 학습 콘텐츠 생성",
        "lstm_tab": "LSTM 성취도 예측 대시보드",
        "sim_tab_chat_email": "AI 고객 응대 시뮬레이터 (채팅/이메일)",
        "sim_tab_phone": "AI 고객 응대 시뮬레이터 (전화)",
        "simulator_tab": "AI 고객 응대 시뮬레이터",
        "company_info_tab": "회사 정보 및 FAQ",
        "company_info_tab_desc": "회사별 상세 정보, 인기 상품, 화제의 소식, FAQ를 검색하고 관리할 수 있는 기능입니다.",
        "sim_tab_chat_email_desc": "고객 응대 업무에서 채팅 및 이메일로 실제로 문의 응대가 될 수 있는 실전 대비 가상 시나리오입니다. AI가 응대 가이드라인과 초안을 생성하며, 고객 반응을 시뮬레이션하여 실전 대비 훈련이 가능합니다.",
        "sim_tab_phone_desc": "고객 응대 업무에서 전화로 실제로 문의 응대가 될 수 있는 실전 대비 가상 시나리오입니다. 음성 녹음 및 실시간 CC 자막 기능을 제공하며, 전화 통화 시뮬레이션을 통해 실전 응대 능력을 향상시킬 수 있습니다.",
        "rag_tab_desc": "업로드된 문서를 기반으로 질문에 답변하는 지식 챗봇입니다. PDF, TXT, HTML 파일을 업로드하여 RAG(Retrieval-Augmented Generation) 인덱스를 구축하고, 문서 내용을 기반으로 정확한 답변을 제공합니다.",
        "content_tab_desc": "AI를 활용하여 개인 맞춤형 학습 콘텐츠를 생성하는 기능입니다. 학습 주제와 난이도에 맞춰 핵심 요약 노트, 객관식 퀴즈, 실습 예제 등을 생성할 수 있습니다.",
        "lstm_tab_desc": "LSTM 모델을 활용하여 학습자의 성취도를 예측하고 대시보드로 시각화하는 기능입니다. 과거 퀴즈 점수 데이터를 분석하여 미래 성취도를 예측하고, 학습 성과를 시각적으로 확인할 수 있습니다.",
        "company_info_tab_desc": "회사별 상세 정보, 인기 상품, 화제의 소식, FAQ를 검색하고 관리할 수 있는 기능입니다. 회사 소개, 인기 상품, 화제의 소식을 시각화하여 한눈에 확인할 수 있습니다.",
        "voice_rec_header_desc": "음성 녹음 및 전사 결과를 관리하고 저장하는 기능입니다. 마이크로 녹음하거나 파일을 업로드하여 Whisper API를 통해 음성을 텍스트로 변환하고, 전사 결과를 저장 및 관리할 수 있습니다.",
        "more_features_label": "더보기 기능",
        "rag_header": "RAG 지식 챗봇 (문서 기반 Q&A)",
        "rag_desc": "업로드된 문서 기반으로 질문에 답변합니다。",
        "rag_input_placeholder": "학습 자료에 대해 질문해 보세요",
        "llm_error_key": "⚠️ 경고: GEMINI API 키가 설정되지 않았습니다. Streamlit Secrets에 'GEMINI_API_KEY'를 설정해주세요。",
        "llm_error_init": "LLM 초기화 오류: API 키를 확인해 주세요。",
        "content_header": "맞춤형 학습 콘텐츠 생성",
        "content_desc": "학습 주제와 난이도에 맞춰 콘텐츠 생성",
        "topic_label": "학습 주제",
        "level_label": "난이도",
        "content_type_label": "콘텐츠 형식",
        "level_options": ["초급", "중급", "고급"],
        "content_options": ["핵심 요약 노트", "객관식 퀴즈 10문항", "실습 예제 아이디어"],
        "button_generate": "콘텐츠 생성",
        "warning_topic": "학습 주제를 입력해 주세요。",
        "lstm_header": "LSTM 기반 학습 성취도 예측 대시보드",
        "lstm_desc": "가상의 과거 퀴즈 점수 데이터를 바탕으로 LSTM 모델을 훈련하고 미래 성취도를 예측하여 보여줍니다。",
        "lang_select": "언어 선택",
        "company_info_faq_settings": "회사별 상세 정보 및 FAQ",
        "search_company": "회사명 검색",
        "company_info": "회사 소개",
        "company_faq": "자주 나오는 질문",
        "faq_question": "질문",
        "faq_answer": "답변",
        "popular_products": "인기 상품",
        "trending_topics": "화제의 소식",
        "company_details": "회사 상세 정보",
        "no_company_found": "에 해당하는 회사를 찾을 수 없습니다.",
        "no_company_selected": "회사명을 검색하거나 선택해주세요.",
        "product_popularity": "상품 인기도",
        "topic_trends": "화제 트렌드",
        "select_company": "회사 선택",
        "faq_search": "FAQ 검색",
        "faq_search_placeholder": "FAQ 검색어를 입력하세요",
        "faq_search_placeholder_extended": "FAQ 검색어를 입력하세요 (상품명, 서비스명 등도 검색 가능)",
        "button_search_faq": "검색",
        "company_search_placeholder": "예: 삼성, 네이버, 구글, 애플 등",
        "company_search_button": "검색",
        "generating_company_info": "회사 정보를 생성하는 중...",
        "button_copy_answer": "답안 복사",
        "button_copy_hint": "힌트 복사",
        "button_download_answer": "답안 다운로드",
        "button_download_hint": "힌트 다운로드",
        "copy_instruction": "💡 위 텍스트를 선택하고 Ctrl+C (Mac: Cmd+C)로 복사하세요.",
        "copy_help_text": "텍스트를 선택하고 Ctrl+C (또는 Cmd+C)로 복사하세요.",
        "button_reset": "새로 시작",
        "answer_displayed": "답안이 표시되었습니다. 위의 텍스트를 복사하세요.",
        "hint_displayed": "힌트가 표시되었습니다. 위의 텍스트를 복사하세요.",
        "ai_answer_generated": "AI 답안이 생성되었습니다.",
        "hint_generated": "응대 힌트가 생성되었습니다.",
        "warning_enter_inquiry": "고객 문의 내용을 입력해주세요.",
        "customer_inquiry_review_desc": "에이전트가 상사들에게 고객 문의 내용을 재확인하고, AI 답안 및 힌트를 생성할 수 있는 기능입니다.",
        "all_companies": "전체",
        "optional": "선택사항",
        "no_faq_for_company": "{company}의 FAQ가 없습니다.",
        "related_products": "관련 상품",
        "related_trending_news": "관련 화제 소식",
        "related_company_info": "관련 회사 소개 내용",
        "related_faq": "관련 FAQ",
        "items": "개",
        "popularity": "인기도",
        "no_faq_for_product": "해당 상품과 관련된 FAQ를 찾을 수 없습니다. 상품 정보만 표시됩니다.",
        "generating_detail": "상세 내용을 생성하는 중입니다...",
        "checking_additional_info": "상세 내용: {topic}에 대한 추가 정보를 확인 중입니다.",
        "button_generate_faq": "FAQ 생성",
        "button_add_company": "고객 문의 재확인",
        "customer_inquiry_review": "고객 문의 재확인",
        "inquiry_question_label": "고객 문의 내용",
        "inquiry_question_placeholder": "고객이 문의한 내용을 입력하세요",
        "inquiry_attachment_label": "📎 고객 첨부 파일 업로드 (사진/스크린샷)",
        "inquiry_attachment_help": "특히 취소 불가 여행상품의 비행기 지연, 여권 이슈 등 불가피한 사유의 경우, 반드시 사진이나 스크린샷을 첨부해주세요.",
        "inquiry_attachment_uploaded": "✅ 첨부 파일이 업로드되었습니다: {filename}",
        "extracting_file_content": "파일 내용 추출 중...",
        "detecting_language": "언어 감지 중...",
        "translating_content": "파일 내용 번역 중...",
        "file_translated": "✅ 파일 내용이 번역되었습니다.",
        "file_extraction_error": "파일 내용 추출 중 오류가 발생했습니다: {error}",
        "ocr_requires_manual": "이미지 OCR을 위해서는 Gemini API 키가 필요합니다. 이미지의 텍스트를 수동으로 입력해주세요.",
        "ocr_error": "이미지 텍스트 추출 중 오류: {error}",
        "button_generate_ai_answer": "AI 답안 생성",
        "button_generate_hint": "응대 힌트 생성",
        "ai_answer_header": "AI 추천 답안",
        "hint_header": "응대 힌트",
        "generating_ai_answer": "AI 답안을 생성하는 중...",
        "generating_hint": "응대 힌트를 생성하는 중...",
        "button_edit_company": "회사 정보 수정",
        "button_show_company_info": "회사 소개 보기",
        "no_faq_results": "검색 결과가 없습니다.",
        "faq_search_results": "FAQ 검색 결과",
        "add_company_name": "회사명",
        "add_company_info": "회사 소개",
        "generate_faq_question": "질문",
        "generate_faq_answer": "답변",
        "button_save_faq": "FAQ 저장",
        "button_cancel": "취소",
        "faq_saved_success": "FAQ가 저장되었습니다.",
        "company_added_success": "회사가 추가되었습니다.",
        "company_updated_success": "회사 정보가 업데이트되었습니다.",
        "interview_questions": "면접 예상 질문",
        "interview_questions_desc": "면접에서 나올 만한 핵심 질문들과 상세한 답변입니다. 면접 준비와 회사 이해에 도움이 됩니다.",
        "interview_category_other": "기타",
        "ceo_info": "CEO/대표이사 정보",
        "position": "직책",
        "tenure": "재임 기간",
        "ceo_bio": "소개",
        "education": "학력",
        "career": "주요 경력",
        "embed_success": "총 {count}개 청크로 학습 DB 구축 완료!",
        "embed_fail": "임베딩 실패: 무료 티어 한도 초과 또는 네트워크 문제。",
        "warning_no_files": "먼저 학습 자료를 업로드하세요。",
        "warning_rag_not_ready": "RAG가 준비되지 않았습니다. 학습 자료를 업로드하고 분석하세요。",
        "quiz_fail_structure": "퀴즈 데이터 구조가 올바르지 않습니다。",
        "select_answer": "정답을 선택하세요",
        "check_answer": "정답 확인",
        "next_question": "다음 문항",
        "correct_answer": "정답입니다! 🎉",
        "incorrect_answer": "오답입니다。😞",
        "correct_is": "정답",
        "explanation": "해설",
        "quiz_complete": "퀴즈 완료!",
        "score": "점수",
        "retake_quiz": "퀴즈 다시 풀기",
        "question_label": "문항",
        "correct_questions": "맞은 문제",
        "incorrect_questions": "틀린 문제",
        "question_result": "문제 결과",
        "your_answer": "내 답안",
        "correct_answer_label": "정답",
        "quiz_error_llm": "퀴즈 생성 실패: LLM이 올바른 JSON 형식을 반환하지 않았습니다。",
        "quiz_original_response": "LLM 원본 응답",
        "firestore_loading": "데이터베이스에서 RAG 인덱스 로드 중...",
        "firestore_no_index": "데이터베이스에서 기존 RAG 인덱스를 찾을 수 없습니다. 파일을 업로드하여 새로 만드세요。",
        "db_save_complete": "(DB 저장 완료)",
        "data_analysis_progress": "자료 분석 및 학습 DB 구축 중...",
        "response_generating": "답변 생성 중...",
        "lstm_result_header": "학습 성취도 예측 결과",
        "lstm_score_metric": "현재 예측 성취도",
        "lstm_score_info": "다음 퀴즈 예상 점수는 약 **{predicted_score:.1f}점**입니다. 학습 성과를 유지하거나 개선하세요!",
        "lstm_rerun_button": "새로운 가상 데이터로 예측",

        # --- 토스트 메시지 추가 ---
        "toast_like": "🔥 컨텐츠가 맘에 드셨군요! (좋아요 카운트 +1)",
        "toast_dislike": "😔 더 나은 콘텐츠를 위해 피드백을 반영하겠습니다。",
        "toast_share": "🌐 콘텐츠 링크가 생성되었습니다。",
        "toast_copy": "✅ 콘텐츠가 클립보드에 복사되었습니다!",
        "toast_more": "ℹ️ 추가 옵션 (PDF, 인쇄본 저장 등)",
        "mock_pdf_save": "📥 PDF 저장",
        "mock_word_open": "📑 Word로 열기",
        "mock_print": "🖨 인쇄",

        # --- 시뮬레이터 ---
        "simulator_header": "AI 고객 응대 시뮬레이터",
        "simulator_desc": "까다로운 고객 문의에 AI의 응대 초안 및 가이드라인을 제공합니다。",
        "customer_query_label": "고객 문의 내용 (링크 포함 가능)",
        "customer_type_label": "고객 성향",
        "customer_type_options": ["일반적인 문의", "까다로운 고객", "매우 불만족스러운 고객"],
        "button_simulate": "응대 조언 요청",
        "customer_generate_response_button": "고객 반응 생성",
        "send_closing_confirm_button": "추가 문의 여부 확인 메시지 보내기",
        "simulation_warning_query": "고객 문의 내용을 입력해 주세요。",
        "simulation_no_key_warning": "⚠️ API Key가 없기 때문에 응답 생성은 실행되지 않습니다。",
        "simulation_advice_header": "AI의 응대 가이드라인",
        "simulation_draft_header": "추천 응대 초안",
        "button_listen_audio": "음성으로 듣기",
        "tts_status_ready": "음성으로 듣기 준비됨",
        "tts_status_generating": "오디오 생성 중...",
        "tts_status_success": "✅ 오디오 재생 완료!",
        "tts_status_error": "❌ TTS 오류 발생",
        "history_expander_title": "📝 이전 상담 이력 로드 (최근 10건)",
        "initial_query_sample": "프랑스 파리에 도착했는데, 클룩에서 구매한 eSIM이 활성화가 안 됩니다...",
        "button_mic_input": "🎙 음성 입력",
        "button_mic_stop": "⏹️ 녹음 종료",
        "prompt_customer_end": "고객님의 추가 문의 사항이 없어, 이 상담을 종료합니다。",
        "prompt_survey": "지금까지 상담원 000였습니다. 즐거운 하루 되시기 바랍니다. [설문 조사 링크]",
        "customer_closing_confirm": "다른 문의 사항은 없으십니까?",
        "customer_positive_response": "알겠습니다. 감사합니다。",
        "button_email_end_chat": "응대 종료 (설문 요청)",
        "error_mandatory_contact": "이메일과 전화번호 입력은 필수입니다。",
        "customer_attachment_label": "📎 고객 첨부 파일 업로드",
        "attachment_info_llm": "[고객 첨부 파일: {filename}이(가) 확인되었습니다. 이 파일을 참고하여 응대하세요.]",
        "button_retry_translation": "번역 다시 시도",
        "button_request_hint": "💡 응대 힌트 요청 (AHT 모니터링 중)",
        "button_generate_draft": "🤖 AI 응답 초안 생성",
        "draft_generating": "AI가 응답 초안을 생성 중입니다...",
        "draft_success": "✅ AI 응답 초안이 생성되었습니다. 아래에서 확인하고 수정하세요.",
        "hint_placeholder": "문의 응대에 대한 힌트:",
        "survey_sent_confirm": "📨 설문조사 링크가 전송되었으며, 이 상담은 종료되었습니다。",
        "new_simulation_ready": "새 시뮬레이션을 시작할 수 있습니다。",
        "agent_response_header": "✍️ 에이전트 응답",
        "agent_response_placeholder": "고객에게 응답하세요...",
        "send_response_button": "응답 전송",
        "customer_turn_info": "에이전트 응답 전송 완료. 고객 반응을 자동으로 생성 중입니다。",
        "generating_customer_response": "고객 반응 생성 중...",
        "call_started_message": "통화가 시작되었습니다. 아래 마이크 버튼을 눌러 인사말을 녹음하세요.",
        "call_on_hold_message": "통화가 Hold 중입니다. 통화 재개 후 녹음이 가능합니다.",
        "recording_complete_transcribing": "🎙️ 녹음 완료. 전사 처리 중...",
        "recording_complete_press_transcribe": "✅ 녹음 완료! 아래 전사 버튼을 눌러 텍스트로 변환하세요.",
        "customer_positive_solution_reaction": "고객이 솔루션에 긍정적으로 반응했습니다. 추가 문의 여부를 확인해 주세요.",
        "transcription_empty_warning": "⚠️ 전사 결과가 비어있습니다. 다시 녹음해주세요. (마이크 입력이 없거나 음소거된 경우)",
        "transcription_error": "[ERROR: 전사 실패]",
        "transcription_no_result": "❌ 전사 결과가 없습니다.",
        "customer_escalation_start": "상급자와 이야기하고 싶습니다",
        "request_rebuttal_button": "고객의 다음 반응 요청",
        "new_simulation_button": "새 시뮬레이션 시작",
        "history_selectbox_label": "로드할 이력을 선택하세요:",
        "history_load_button": "선택된 이력 로드",
        "delete_history_button": "❌ 모든 이력 삭제",
        "delete_confirm_message": "정말로 모든 상담 이력을 삭제하시겠습니까?",
        "delete_confirm_yes": "예, 삭제합니다",
        "download_history_word": "📥 이력 다운로드 (Word)",
        "download_history_pptx": "📥 이력 다운로드 (PPTX)",
        "download_history_pdf": "📥 이력 다운로드 (PDF)",
        "download_current_session": "📥 현재 세션 다운로드",
        "delete_confirm_no": "아니오, 유지합니다",
        "delete_success": "✅ 삭제 완료!",
        "deleting_history_progress": "이력 삭제 중...",
        "search_history_label": "이력 검색",
        "date_range_label": "날짜 범위 필터",
        "history_search_button": "🔍 검색",
        "no_history_found": "검색 조건에 맞는 이력이 없습니다。",
        "customer_email_label": "고객 이메일 (필수)",
        "customer_phone_label": "고객 연락처 / 전화번호 (필수)",
        "transfer_header": "언어 이관 요청 (다른 팀)",
        "transfer_to_en": "🇺🇸 영어 팀으로 이관",
        "transfer_to_ja": "🇯🇵 일본어 팀으로 이관",
        "transfer_to_ko": "🇰🇷 한국어 팀으로 이관",
        "transfer_system_msg": "📌 시스템 메시지: 고객 요청에 따라 상담 언어가 {target_lang} 팀으로 이관되었습니다. 새로운 상담원(AI)이 응대합니다。",
        "transfer_loading": "이관 처리 중: 이전 대화 이력 번역 및 검토 (고객님께 3~10분 양해 요청)",
        "transfer_summary_header": "🔍 이관된 상담원을 위한 요약 (번역됨)",
        "transfer_summary_intro": "고객님과의 이전 대화 이력입니다. 이 내용을 바탕으로 응대를 이어나가세요。",
        "llm_translation_error": "❌ 번역 실패: LLM 응답 오류",
        "timer_metric": "상담 경과 시간 (AHT)",
        "timer_info_ok": "AHT (15분 기준)",
        "timer_info_warn": "AHT (10분 초과)",
        "timer_info_risk": "🚨 15분 초과: 높은 리스크",
        "solution_check_label": "✅ 이 응답에 솔루션/해결책이 포함되어 있습니다。",
        "sentiment_score_label": "고객 감정 점수",
        "urgency_score_label": "긴급도 점수",
        "customer_gender_label": "고객 성별",
        "customer_emotion_label": "고객 감정 상태",
        "gender_male": "남성",
        "gender_female": "여성",
        "emotion_happy": "기분 좋은 고객",
        "emotion_dissatisfied": "불만인 고객",
        "emotion_angry": "화난 고객",
        "emotion_sad": "슬픈/우울한 고객",
        "emotion_neutral": "중립",
        "similarity_chart_title": "유사 케이스 유사도",
        "scores_comparison_title": "감정 및 만족도 점수 비교",
        "similarity_score_label": "유사도",
        "satisfaction_score_label": "만족도",
        "customer_satisfaction_score_label": "고객 만족도 점수",
        "sentiment_trend_label": "감정 점수 추이",
        "satisfaction_trend_label": "만족도 점수 추이",
        "case_trends_title": "과거 케이스 점수 추이",
        "date_label": "날짜",
        "score_label": "점수 (0-100)",
        "customer_characteristics_title": "고객 특성 분포",
        "language_label": "언어",
        "email_provided_label": "이메일 제공",
        "phone_provided_label": "전화번호 제공",
        "region_label": "지역",
        "btn_request_phone_summary": "이력 요약 요청",
        
        # --- 다운로드 문서 관련 텍스트 ---
        "download_history_title": "고객 응대 이력 요약",
        "download_history_number": "이력 #",
        "download_initial_inquiry": "초기 문의",
        "download_summary": "요약",
        "download_main_inquiry": "주요 문의",
        "download_key_response": "핵심 응답",
        "download_customer_characteristics": "고객 특성",
        "download_privacy_summary": "개인정보 요약",
        "download_address_provided": "주소 제공",
        "download_overall_summary": "전체 요약",
        "download_yes": "예",
        "download_no": "아니오",
        "download_created_date": "생성일",
        "download_cultural_background": "문화적 배경",
        "download_communication_style": "소통 스타일",
        "download_region_hint": "지역 힌트",

        # --- 추가된 전화 발신 기능 관련 ---
        "button_call_outbound": "전화 발신",
        "button_call_outbound_to_customer": "고객에게 전화 발신",
        "button_call_outbound_to_provider": "현지 업체에게 전화 발신",
        "call_outbound_system_msg": "📌 시스템 메시지: 에이전트가 {target}에게 전화 발신을 시도했습니다。",
        "call_outbound_simulation_header": "📞 전화 발신 시뮬레이션 결과",
        "call_outbound_summary_header": "📞 현지 업체/고객과의 통화 요약",
        "call_outbound_loading": "전화 연결 및 통화 결과 정리 중... (LLM 호출)",
        "call_target_select_label": "발신 대상 선택",
        "call_target_customer": "고객에게 발신",
        "call_target_partner": "현지 업체 발신",

        # --- 음성 기록 ---
        "voice_rec_header": "음성 기록 & 관리",
        "record_help": "마이크 버튼을 눌러 녹음하거나 파일을 업로드하세요。",
        "uploaded_file": "오디오 파일 업로드",
        "rec_list_title": "저장된 음성 기록",
        "transcribe_btn": "전사(Whisper)",
        "save_btn": "음성 기록 저장",
        "transcribing": "음성 전사 중...",
        "transcript_result": "전사 결과:",
        "transcript_text": "전사 텍스트",
        "openai_missing": "OpenAI API Key가 없습니다。",
        "whisper_client_error": "❌ Whisper API Client 초기화 실패",
        "whisper_auth_error": "❌ Whisper API 인증 실패",
        "whisper_format_error": "❌ 지원하지 않는 오디오 형식입니다。",
        "whisper_success": "✅ 음성 전사 완료!",
        "playback": "녹음 재생",
        "retranscribe": "재전사",
        "delete": "삭제",
        "no_records": "저장된 음성 기록이 없습니다。",
        "saved_success": "저장 완료!",
        "delete_confirm_rec": "정말 삭제하시겠습니까?",
        "gcs_not_conf": "GCS 미설정",
        "gcs_playback_fail": "오디오 재생 실패",
        "gcs_no_audio": "오디오 없음",
        "error": "오류:",
        "firestore_no_db_connect": "DB 연결 실패",
        "save_history_success": "상담 이력이 저장되었습니다。",
        "save_history_fail": "상담 이력 저장 실패",
        "delete_fail": "삭제 실패",
        "rec_header": "음성 입력 및 전사",
        "whisper_processing": "음성 전사 처리 중..",
        "empty_response_warning": "응답을 입력하세요.",
        "customer_no_more_inquiries": "없습니다. 감사합니다.",
        "customer_has_additional_inquiries": "추가 문의 사항도 있습니다.",
        "sim_end_chat_button": "설문 조사 링크 전송 및 응대 종료",
        "delete_mic_record": "❌ 녹음 삭제",
        "agent_confirmed_additional_inquiry": "에이전트가 추가 문의 여부를 확인했습니다. 고객의 최종 답변을 자동으로 생성합니다.",
        "llm_key_missing_customer_response": "LLM Key가 없어 고객 반응 자동 생성이 불가합니다. 수동으로 '고객 반응 생성' 버튼을 클릭하거나 AGENT_TURN으로 돌아가세요。",
        "customer_response_generation_failed": "고객 응답을 생성할 수 없습니다. 다시 시도해주세요.",
        "no_more_inquiries_confirmed": "✅ 고객이 더 이상 문의할 사항이 없다고 확인했습니다。",
        "consultation_end_header": "📋 상담 종료",
        "click_survey_button_to_end": "아래 **설문 조사 링크 전송 및 응대 종료** 버튼을 클릭하여 상담을 종료하세요.",

        # --- 첨부 파일 기능 추가 ---
        "attachment_label": "고객 첨부 파일 업로드 (스크린샷 등)",
        "attachment_placeholder": "파일을 첨부하여 상황을 설명하세요 (선택 사항)",
        "attachment_info_llm": "[고객 첨부 파일: {filename}이(가) 확인되었습니다. 이 파일을 참고하여 응대하세요.]",
        "agent_attachment_label": "에이전트 첨부 파일 (스크린샷 등)",
        "agent_attachment_placeholder": "응답에 첨부할 파일을 선택하세요 (선택 사항)",
        "agent_attachment_status": "📎 에이전트가 **{filename}** 파일을 응답에 첨부했습니다. (파일 타입: {filetype})",

        # --- RAG 오류 메시지 추가 ---
        "rag_embed_error_openai": "RAG 임베딩 실패: OpenAI API Key가 유효하지 않거나 설정되지 않았습니다。",
        "rag_embed_error_gemini": "RAG 임베딩 실패: Gemini API Key가 유효하지 않거나 설정되지 않았습니다。",
        "rag_embed_error_nvidia": "RAG 임베딩 실패: NVIDIA API Key가 유효하지 않거나 설정되지 않았습니다。",
        "rag_embed_error_none": "RAG 임베딩에 필요한 모든 키(OpenAI, Gemini, NVIDIA)가 유효하지 않습니다. 키를 설정해 주세요。",

        # --- 전화 기능 관련 추가 ---
        "phone_header": "AI 고객 응대 시뮬레이터 (전화)",
        "call_status_waiting": "수신 대기 중...",
        "call_status_ringing": "전화 수신 중: {number}",
        "button_answer": "📞 전화 응답",
        "button_hangup": "🔴 전화 끊기",
        "button_hold": "⏸️ Hold (소음 차단)",
        "button_resume": "▶️ 통화 재개",
        "hold_status": "통화 Hold 중 (누적 Hold 시간: {duration})",
        "cc_live_transcript": "🎤 실시간 CC 자막 / 전사",
        "mic_input_status": "🎙️ 에이전트 음성 입력",
        "customer_audio_playback": "🗣️ 고객 음성 재생",
        "agent_response_prompt": "고객에게 말할 응답을 녹음하세요。",
        "agent_response_stop_and_send": "⏹️ 녹음 종료 및 응답 전송",
        "call_end_message": "통화가 종료되었습니다. AHT 및 이력을 확인하세요。",
        "call_query_placeholder": "고객 문의 내용을 입력하세요。",
        "call_number_placeholder": "+82 10-xxxx-xxxx (가상 번호)",
        "website_url_label": "홈페이지 웹 주소 (선택사항)",
        "website_url_placeholder": "https://example.com (홈페이지 주소가 있으면 입력하세요)",
        "call_summary_header": "AI 통화 요약",
        "customer_audio_header": "고객 최초 문의 (음성)",
        "aht_not_recorded": "⚠️ 통화 시작 시간이 기록되지 않아 AHT를 계산할 수 없습니다。",
        "no_audio_record": "고객의 최초 음성 기록이 없습니다。",
        "customer_query_playing": "🔊 고객 문의 재생 중입니다.",
        "query_content_label": "📝 문의 내용:",
        "auto_play_failed": "자동 재생 실패: {error}. 수동으로 재생해주세요.",
        "generating_customized_response": "고객 맞춤형 반응 생성 중...",
        "customer_responded": "🗣️ 고객이 응답했습니다: {reaction}",
        "customer_voice_generation_error": "❌ 고객 음성 생성 오류: {error}",
        "button_retry_translation": "번역 다시 시도",
        "customer_waiting_hold": "[고객: 잠시 대기 중입니다...]",
        "agent_hold_message": "[에이전트: Hold 중입니다. 통화 재개 버튼을 눌러주세요.]",
        
        # --- 비디오 파일 업로드 관련 ---
        "video_upload_expander": "비디오 파일 업로드/로드",
        "video_sync_enable": "비디오 동기화 활성화 (TTS와 함께 재생)",
        "video_rag_title": "🎥 OpenAI/Gemini 기반 영상 RAG 기능",
        "video_rag_desc": "✅ **현재 구현 방식 (영상 RAG):**\n\n1. **LLM 텍스트 분석**: OpenAI/Gemini API가 고객의 텍스트를 분석하여 감정 상태와 제스처를 자동 판단합니다.\n\n2. **지능형 비디오 선택**: 분석 결과에 따라 적절한 비디오 클립을 자동으로 선택합니다.\n   - 감정 상태: HAPPY, ANGRY, ASKING, SAD, NEUTRAL\n   - 제스처: HAND_WAVE, NOD, SHAKE_HEAD, POINT, NONE\n\n3. **TTS 동기화 재생**: 선택된 비디오와 TTS로 생성된 음성을 동시에 재생합니다.\n\n**사용 방법:**\n- 성별(남자/여자)과 감정 상태별로 비디오 파일을 업로드하세요.\n- 제스처별 비디오도 업로드 가능합니다 (예: `male_happy_hand_wave.mp4`).\n- 고객이 말하는 내용에 따라 LLM이 자동으로 적절한 비디오를 선택합니다.",
        "video_gender_emotion_setting": "성별 및 감정 상태별 비디오 설정",
        "video_gender_label": "성별",
        "video_gender_male": "남자",
        "video_gender_female": "여자",
        "video_emotion_label": "감정 상태",
        "video_upload_label": "비디오 파일 업로드 ({gender} - {emotion})",
        "video_current_selection": "📹 현재 선택: {gender} - {emotion}",
        "video_upload_prompt": "💡 '{filename}' 비디오 파일을 업로드하세요.",
        "video_save_path": "📂 비디오 저장 경로:",
        "video_directory_empty": "⚠️ 비디오 디렉토리에 파일이 없습니다. 파일을 업로드하세요.",
        "video_directory_not_exist": "⚠️ 비디오 디렉토리가 존재하지 않습니다: {path}",
        "video_local_path_input": "또는 로컬 파일 경로 입력",
        "video_local_path_placeholder": "예: C:\\Users\\Admin\\Downloads\\video.mp4 또는 video.mp4",
        "video_current_avatar": "📺 현재 고객 아바타 영상",
        "video_avatar_upload_prompt": "💡 '{filename}' 비디오 파일을 업로드하면 영상이 표시됩니다.",
        "video_uploaded_files": "📁 업로드된 비디오 파일:",
        "video_bytes_saved": "✅ 비디오 바이트 저장 완료: {name} ({size} MB)",
        "video_empty_error": "❌ 비디오 파일이 비어있습니다. 다시 업로드해주세요.",
        "video_upload_error": "❌ 비디오 업로드 중 오류 발생: {error}",
        "video_playback_error": "❌ 비디오 재생에 실패했습니다.",
        "video_auto_play_info": "💡 이 비디오는 '{gender} - {emotion}' 상태에서 자동으로 재생됩니다.",
        "video_preview_error": "비디오 미리보기 오류",
        "video_similar_gender": "같은 성별의 다른 비디오",
        "video_rename_hint": "💡 위 비디오 중 하나를 사용하려면 파일명을 변경하거나 새로 업로드하세요.",
        "video_more_files": "... 외 {count}개",
        "avatar_status_info": "상태: {state} | 성별: {gender}",
        "customer_video_simulation": "고객 영상 시뮬레이션",
        "customer_avatar": "고객 아바타",
        "faq_question_prefix": "Q{num}.",
        "visualization_chart": "시각화 차트",
        "company_search_or_select": "회사명을 검색하거나 선택해주세요.",
    },

    # --- ⭐ 영어 버전 (한국어 100% 매칭) ---
    "en": {
        "title": "Personalized AI Study Coach (Voice & Local DB)",
        "sidebar_title": "📚 AI Study Coach Settings",
        "file_uploader": "Upload Study Materials (PDF, TXT, HTML)",
        "button_start_analysis": "Start Analysis (RAG Indexing)",
        "rag_tab": "RAG Knowledge Chatbot",
        "content_tab": "Custom Content Generation",
        "lstm_tab": "LSTM Achievement Prediction Dashboard",
        "sim_tab_chat_email": "AI Customer Support Simulator (Chat / Email)",
        "sim_tab_phone": "AI Customer Support Simulator (Phone)",
        "simulator_tab": "AI Customer Support Simulator",
        "company_info_tab": "Company Information & FAQ",
        "sim_tab_chat_email_desc": "A virtual scenario for practical training in handling customer inquiries via chat and email in customer service work. AI generates response guidelines and drafts, and simulates customer reactions for real-world training.",
        "sim_tab_phone_desc": "A virtual scenario for practical training in handling customer inquiries via phone in customer service work. Provides voice recording and real-time CC subtitle features, allowing you to improve your practical response skills through phone call simulations.",
        "rag_tab_desc": "A knowledge chatbot that answers questions based on uploaded documents. Upload PDF, TXT, or HTML files to build a RAG (Retrieval-Augmented Generation) index and provide accurate answers based on document content.",
        "content_tab_desc": "A feature that generates personalized learning content using AI. You can generate key summary notes, multiple-choice quizzes, and practical examples tailored to learning topics and difficulty levels.",
        "lstm_tab_desc": "A feature that predicts learner achievement using LSTM models and visualizes it in a dashboard. Analyzes past quiz score data to predict future achievement and visually check learning performance.",
        "company_info_tab_desc": "Search and manage company-specific detailed information, popular products, trending news, and FAQs. Visualize company introductions, popular products, and trending news at a glance.",
        "voice_rec_header_desc": "A feature for managing and storing voice recordings and transcription results. Record with a microphone or upload files to convert speech to text via Whisper API, and save and manage transcription results.",
        "more_features_label": "More Features",
        "rag_header": "RAG Knowledge Chatbot (Document Q&A)",
        "rag_desc": "Answer questions based on uploaded documents.",
        "rag_input_placeholder": "Ask a question about your study materials",
        "llm_error_key": "⚠️ Warning: GEMINI_API_KEY is not set.",
        "llm_error_init": "LLM initialization error. Please check your API key.",
        "content_header": "Custom Learning Content Generation",
        "content_desc": "Generate content based on the topic and difficulty.",
        "topic_label": "Learning Topic",
        "level_label": "Difficulty",
        "content_type_label": "Content Type",
        "level_options": ["Beginner", "Intermediate", "Advanced"],
        "content_options": ["Key Summary Note", "10 MCQ Questions", "Practical Example Idea"],
        "button_generate": "Generate Content",
        "warning_topic": "Please enter a learning topic.",
        "lstm_header": "LSTM Achievement Prediction Dashboard",
        "lstm_desc": "Train an LSTM model on hypothetical quiz scores and predict performance.",
        "lang_select": "Select Language",
        "company_info_faq_settings": "Company Details & FAQ",
        "search_company": "Search Company",
        "company_info": "Company Information",
        "company_faq": "Frequently Asked Questions",
        "faq_question": "Question",
        "faq_answer": "Answer",
        "popular_products": "Popular Products",
        "trending_topics": "Trending News",
        "company_details": "Company Details",
        "no_company_found": "No matching company found.",
        "no_company_selected": "Please search or select a company name.",
        "product_popularity": "Product Popularity",
        "topic_trends": "Topic Trends",
        "select_company": "Select Company",
        "faq_search": "FAQ Search",
        "faq_search_placeholder": "Enter FAQ search term",
        "faq_search_placeholder_extended": "Enter FAQ search term (product names, service names, etc. can also be searched)",
        "button_search_faq": "Search",
        "company_search_placeholder": "e.g., Samsung, Naver, Google, Apple",
        "company_search_button": "Search",
        "generating_company_info": "Generating company information...",
        "button_copy_answer": "Copy Answer",
        "button_copy_hint": "Copy Hint",
        "button_download_answer": "Download Answer",
        "button_download_hint": "Download Hint",
        "copy_instruction": "💡 Select the text above and press Ctrl+C (Mac: Cmd+C) to copy.",
        "copy_help_text": "Select the text and press Ctrl+C (or Cmd+C) to copy.",
        "button_reset": "Reset",
        "answer_displayed": "Answer displayed. Please copy the text above.",
        "hint_displayed": "Hint displayed. Please copy the text above.",
        "ai_answer_generated": "AI answer has been generated.",
        "hint_generated": "Response hint has been generated.",
        "warning_enter_inquiry": "Please enter the customer inquiry.",
        "customer_inquiry_review_desc": "A feature that allows agents to reconfirm customer inquiries with supervisors and generate AI answers and hints.",
        "all_companies": "All",
        "optional": "Optional",
        "no_faq_for_company": "No FAQs available for {company}.",
        "related_products": "Related Products",
        "related_trending_news": "Related Trending News",
        "related_company_info": "Related Company Information",
        "related_faq": "Related FAQ",
        "items": "",
        "popularity": "Popularity",
        "no_faq_for_product": "No FAQs related to this product were found. Only product information is displayed.",
        "generating_detail": "Generating detailed content...",
        "checking_additional_info": "Checking additional information for: {topic}",
        "button_generate_faq": "Generate FAQ",
        "button_add_company": "Customer Inquiry Review",
        "customer_inquiry_review": "Customer Inquiry Review",
        "inquiry_question_label": "Customer Inquiry",
        "inquiry_question_placeholder": "Enter the customer's inquiry",
        "inquiry_attachment_label": "📎 Customer Attachment Upload (Photo/Screenshot)",
        "inquiry_attachment_help": "For non-refundable travel products with unavoidable reasons (flight delays, passport issues, etc.), please attach photos or screenshots.",
        "inquiry_attachment_uploaded": "✅ Attachment uploaded: {filename}",
        "extracting_file_content": "Extracting file content...",
        "detecting_language": "Detecting language...",
        "translating_content": "Translating file content...",
        "file_translated": "✅ File content has been translated.",
        "file_extraction_error": "Error occurred while extracting file content: {error}",
        "ocr_requires_manual": "Gemini API key is required for image OCR. Please manually enter the text from the image.",
        "ocr_error": "Error extracting text from image: {error}",
        "button_generate_ai_answer": "Generate AI Answer",
        "button_generate_hint": "Generate Response Hint",
        "ai_answer_header": "AI Recommended Answer",
        "hint_header": "Response Hint",
        "generating_ai_answer": "Generating AI answer...",
        "generating_hint": "Generating response hint...",
        "button_edit_company": "Edit Company Info",
        "button_show_company_info": "Show Company Info",
        "no_faq_results": "No search results found.",
        "faq_search_results": "FAQ Search Results",
        "add_company_name": "Company Name",
        "add_company_info": "Company Information",
        "generate_faq_question": "Question",
        "generate_faq_answer": "Answer",
        "button_save_faq": "Save FAQ",
        "button_cancel": "Cancel",
        "faq_saved_success": "FAQ saved successfully.",
        "company_added_success": "Company added successfully.",
        "company_updated_success": "Company information updated successfully.",
        "interview_questions": "Interview Questions",
        "interview_questions_desc": "Core questions likely to be asked in interviews with detailed answers. Helps with interview preparation and company understanding.",
        "interview_category_other": "Other",
        "ceo_info": "CEO/President Information",
        "position": "Position",
        "tenure": "Tenure",
        "ceo_bio": "Introduction",
        "education": "Education",
        "career": "Major Career",
        "embed_success": "Learning DB built with {count} chunks!",
        "embed_fail": "Embedding failed: quota exceeded or network issue.",
        "warning_no_files": "Please upload study materials first.",
        "warning_rag_not_ready": "RAG is not ready. Upload materials and analyze.",
        "quiz_fail_structure": "Quiz data structure is invalid.",
        "select_answer": "Select answer",
        "check_answer": "Check answer",
        "next_question": "Next question",
        "correct_answer": "Correct! 🎉",
        "incorrect_answer": "Incorrect 😞",
        "correct_is": "Correct answer",
        "explanation": "Explanation",
        "quiz_complete": "Quiz Complete!",
        "score": "Score",
        "retake_quiz": "Retake Quiz",
        "question_label": "Question",
        "correct_questions": "Correct",
        "incorrect_questions": "Incorrect",
        "question_result": "Question Results",
        "your_answer": "Your Answer",
        "correct_answer_label": "Correct Answer",
        "quiz_error_llm": "Quiz generation failed: invalid JSON.",
        "quiz_original_response": "Original LLM Response",
        "firestore_loading": "Loading RAG index...",
        "firestore_no_index": "No existing RAG index found.",
        "db_save_complete": "(DB Save Complete)",
        "data_analysis_progress": "Analyzing materials and building DB...",
        "response_generating": "Generating response...",
        "lstm_result_header": "Achievement Prediction",
        "lstm_score_metric": "Predicted Achievement",
        "lstm_score_info": "Estimated next quiz score: **{predicted_score:.1f}**.",
        "lstm_rerun_button": "Predict with New Data",

        # --- 토스트 메시지 추가 ---
        "toast_like": "🔥 Content liked! (+1 Count Reflected)",
        "toast_dislike": "😔 Feedback recorded for better content.",
        "toast_share": "🌐 Content link generated.",
        "toast_copy": "✅ Content copied to clipboard!",
        "toast_more": "ℹ️ Additional options (Print, PDF Save, etc.)",
        "mock_pdf_save": "📥 Save as PDF",
        "mock_word_open": "📑 Open via Word",
        "mock_print": "🖨 Print",

        # --- 토스트 메시지 끝 ---

        # Simulator
        "simulator_header": "AI Customer Response Simulator",
        "simulator_desc": "AI generates draft responses and guidelines for customer inquiries.",
        "customer_query_label": "Customer Message (links allowed)",
        "customer_type_label": "Customer Type",
        "customer_type_options": ["General Inquiry", "Difficult Customer", "Highly Dissatisfied Customer"],
        "button_simulate": "Generate Response",
        "customer_generate_response_button": "Generate Customer Response",
        "send_closing_confirm_button": "Send Closing Confirmation",
        "simulation_warning_query": "Please enter the customer’s message.",
        "simulation_no_key_warning": "⚠️ API Key missing. Simulation cannot proceed.",
        "simulation_advice_header": "AI Response Guidelines",
        "simulation_draft_header": "Recommended Response Draft",
        "button_listen_audio": "Play as Audio",
        "tts_status_ready": "Ready to generate audio",
        "tts_status_generating": "Generating audio...",
        "tts_status_success": "Audio ready!",
        "tts_status_error": "TTS error occurred",
        "history_expander_title": "📝 Load Previous Sessions (Last 10)",
        "initial_query_sample": "I arrived in Paris but my Klook eSIM won't activate…",
        "button_mic_input": "🎙 Voice Input",
        "button_mic_stop": "⏹️ Stop recording",
        "prompt_customer_end": "No further inquiries. Ending chat.",
        "prompt_survey": "This was Agent 000. Have a nice day. [Survey Link]",
        "customer_closing_confirm": "Is there anything else we can assist you with?",
        "customer_positive_response": "I understand. Thank you.",
        "button_email_end_chat": "End supports (Survey Request)",
        "error_mandatory_contact": "Email and Phone number input are mandatory.",
        "customer_attachment_label": "📎 Customer Attachment Upload",
        "attachment_info_llm": "[Customer Attachment: {filename} is confirmed. Reference this file in your response.]",
        "button_retry_translation": "Retry Translation",
        "button_request_hint": "💡 Request Response Hint (AHT Monitored)",
        "button_generate_draft": "🤖 Generate AI Response Draft",
        "draft_generating": "AI is generating a response draft...",
        "draft_success": "✅ AI response draft has been generated. Please review and modify below.",
        "hint_placeholder": "Hints for responses",
        "survey_sent_confirm": "📨 The survey link has been sent. This chat session is now closed。",
        "new_simulation_ready": "You can now start a new simulation.",
        "agent_response_header": "✍️ Agent Response",
        "agent_response_placeholder": "Write a response...",
        "send_response_button": "Send Response",
        "customer_turn_info": "Agent response sent. Generating customer reaction automatically。",
        "generating_customer_response": "Generating customer response...",
        "call_started_message": "Call started. Please click the microphone button below to record your greeting.",
        "call_on_hold_message": "Call is on hold. Recording is available after resuming the call.",
        "recording_complete_transcribing": "🎙️ Recording complete. Transcribing...",
        "recording_complete_press_transcribe": "✅ Recording complete! Press the transcribe button below to convert to text.",
        "customer_positive_solution_reaction": "The customer responded positively to the solution. Please check if there are any additional inquiries.",
        "transcription_empty_warning": "⚠️ Transcription result is empty. Please record again. (No microphone input or muted)",
        "transcription_error": "[ERROR: Transcription failed]",
        "transcription_no_result": "❌ No transcription result.",
        "customer_escalation_start": "I want to speak to a supervisor",
        "request_rebuttal_button": "Request Customer Reaction",
        "new_simulation_button": "Start New Simulation",
        "history_selectbox_label": "Choose a record to load:",
        "history_load_button": "Load Selected Record",
        "delete_history_button": "❌ Delete All History",
        "delete_confirm_message": "Are you sure you want to delete all records?",
        "delete_confirm_yes": "Yes, Delete",
        "delete_confirm_no": "Cancel",
        "download_history_word": "📥 Download History (Word)",
        "download_history_pptx": "📥 Download History (PPTX)",
        "download_history_pdf": "📥 Download History (PDF)",
        "download_current_session": "📥 Download Current Session",
        "delete_success": "Deleted successfully!",
        "deleting_history_progress": "Deleting history...",
        "search_history_label": "Search History",
        "date_range_label": "Date Filter",
        "history_search_button": "🔍 Search",
        "no_history_found": "No matching history found.",
        "customer_email_label": "Customer Email (Mandatory)",
        "customer_phone_label": "Customer Phone / WhatsApp (Mandatory)",
        "transfer_header": "Language Transfer Request (To Other Teams)",
        "transfer_to_en": "🇺🇸 English Team Transfer",
        "transfer_to_ja": "🇯🇵 Japanese Team Transfer",
        "transfer_to_ko": "🇰🇷 Korean Team Transfer",
        "transfer_system_msg": "📌 System Message: The session language has been transferred to the {target_lang} team per customer request. A new agent (AI) will now respond。",
        "transfer_loading": "Transferring: Translating and reviewing chat history (3-10 minute wait requested from customer)",
        "transfer_summary_header": "🔍 Summary for Transferred Agent (Translated)",
        "transfer_summary_intro": "This is the previous chat history. Please continue the support based on this summary。",
        "llm_translation_error": "❌ Translation failed: LLM response error",
        "timer_metric": "Elapsed Time",
        "timer_info_ok": "AHT (15 min standard)",
        "timer_info_warn": "AHT (Over 10 min)",
        "timer_info_risk": "🚨 Over 15 min: High Risk",
        "solution_check_label": "✅ This response includes a solution/fix。",
        "sentiment_score_label": "Customer Sentiment Score",
        "urgency_score_label": "Urgency Score",
        "customer_gender_label": "Customer Gender",
        "customer_emotion_label": "Customer Emotional State",
        "gender_male": "Male",
        "gender_female": "Female",
        "emotion_happy": "Happy Customer",
        "emotion_dissatisfied": "Dissatisfied Customer",
        "emotion_angry": "Angry Customer",
        "emotion_sad": "Sad/Depressed Customer",
        "emotion_neutral": "Neutral",
        "similarity_chart_title": "Case Similarity",
        "scores_comparison_title": "Sentiment & Satisfaction Scores",
        "similarity_score_label": "Similarity",
        "satisfaction_score_label": "Satisfaction",
        "customer_satisfaction_score_label": "Customer Satisfaction Score",
        "sentiment_trend_label": "Sentiment Trend",
        "satisfaction_trend_label": "Satisfaction Trend",
        "case_trends_title": "Case Score Trends",
        "date_label": "Date",
        "score_label": "Score (0-100)",
        "customer_characteristics_title": "Customer Characteristics",
        "language_label": "Language",
        "email_provided_label": "Email Provided",
        "phone_provided_label": "Phone Provided",
        "region_label": "Region",
        "btn_request_phone_summary": "Request to summarize histories",
        
        # --- 다운로드 문서 관련 텍스트 ---
        "download_history_title": "Customer Interaction History Summary",
        "download_history_number": "History #",
        "download_initial_inquiry": "Initial Inquiry",
        "download_summary": "Summary",
        "download_main_inquiry": "Main Inquiry",
        "download_key_response": "Key Response",
        "download_customer_characteristics": "Customer Characteristics",
        "download_privacy_summary": "Privacy Summary",
        "download_address_provided": "Address Provided",
        "download_overall_summary": "Overall Summary",
        "download_yes": "Yes",
        "download_no": "No",
        "download_created_date": "Created Date",
        "download_cultural_background": "Cultural Background",
        "download_communication_style": "Communication Style",
        "download_region_hint": "Region Hint",

        # --- 추가된 전화 발신 기능 관련 ---
        "button_call_outbound": "Call Outbound",
        "button_call_outbound_to_customer": "Call Outbound to Customer",
        "button_call_outbound_to_provider": "Call Outbound to Provider",
        "call_outbound_system_msg": "📌 System Message: Agent attempted an outbound call to {target}。",
        "call_outbound_simulation_header": "📞 Outbound Call Simulation Result",
        "call_outbound_summary_header": "📞 Summary of Call with Local Partner/Customer",
        "call_outbound_loading": "Connecting call and summarizing outcome... (LLM Call)",
        "call_target_select_label": "Select Call Target",
        "call_target_customer": "Call Customer",
        "call_target_partner": "Call Local Partner",

        # --- 음성 기록 ---
        "voice_rec_header": "Voice Record & Management",
        "record_help": "Record using the microphone or upload a file。",
        "uploaded_file": "Upload Audio File",
        "rec_list_title": "Saved Voice Records",
        "transcribe_btn": "Transcribe (Whisper)",
        "save_btn": "Save Record",
        "transcribing": "Transcribing...",
        "transcript_result": "Transcription:",
        "transcript_text": "Transcribed Text",
        "openai_missing": "OpenAI API Key is missing。",
        "whisper_client_error": "❌ Error: Whisper API client not initialized。",
        "whisper_auth_error": "❌ Whisper API authentication failed。",
        "whisper_format_error": "❌ Error: Unsupported audio format。",
        "whisper_success": "✅ Voice Transcription Complete!",
        "playback": "Playback Recording",
        "retranscribe": "Re-transcribe",
        "delete": "Delete",
        "no_records": "No saved voice records。",
        "saved_success": "Saved successfully!",
        "delete_confirm_rec": "Are you sure you want to delete this voice record?",
        "gcs_not_conf": "GCS not configured or no audio available",
        "gcs_playback_fail": "Failed to play audio",
        "gcs_no_audio": "No audio file found",
        "error": "Error:",
        "firestore_no_db_connect": "DB connection failed",
        "save_history_success": "Saved successfully。",
        "save_history_fail": "Save failed。",
        "delete_fail": "Delete failed",
        "rec_header": "Voice Input & Transcription",
        "whisper_processing": "Processing...",
        "empty_response_warning": "Please enter a response。",
        "customer_no_more_inquiries": "No, that will be all, thank you。",
        "customer_has_additional_inquiries": "Yes, I have an additional question。",
        "sim_end_chat_button": "Send Survey Link and End Consultations",
        "delete_mic_record": "❌ Delete recordings",
        "agent_confirmed_additional_inquiry": "The agent has confirmed if there are any additional inquiries. Automatically generating the customer's final response.",
        "llm_key_missing_customer_response": "LLM Key is missing. Customer response auto-generation is unavailable. Please manually click the 'Generate Customer Response' button or return to AGENT_TURN。",
        "customer_response_generation_failed": "Failed to generate customer response. Please try again.",
        "no_more_inquiries_confirmed": "✅ Confirmed that the customer has no further inquiries。",
        "consultation_end_header": "📋 End of Consultation",
        "click_survey_button_to_end": "Please end the consultation by clicking the **Send Survey Link and End Consultations** button below.",

        # --- 첨부 파일 기능 추가 ---
        "attachment_label": "Customer Attachment Upload (Screenshot, etc。)",
        "attachment_placeholder": "Attach a file to explain the situation (optional)",
        "attachment_info_llm": "[Customer Attachment: {filename} is confirmed. Reference this file in your response。]",
        "agent_attachment_label": "Agent Attachment (Screenshot, etc。)",
        "agent_attachment_placeholder": "Select a file to attach to the response (optional)",
        "agent_attachment_status": "📎 Agent attached **{filename}** file to the response。 (File type: {filetype})",

        # --- RAG 오류 메시지 추가 ---
        "rag_embed_error_openai": "RAG embedding failed: OpenAI API Key is invalid or not set。",
        "rag_embed_error_gemini": "RAG embedding failed: Gemini API Key is invalid or not set。",
        "rag_embed_error_nvidia": "RAG embedding failed: NVIDIA API Key is invalid or not set。",
        "rag_embed_error_none": "RAG embedding failed: All required keys (OpenAI, Gemini, NVIDIA) are invalid or not set。 Please configure a key。",

        # --- 전화 기능 관련 추가 ---
        "phone_header": "AI Customer Support Simulator (Phone)",
        "call_status_waiting": "Waiting for incoming call...",
        "call_status_ringing": "Incoming Call from: {number}",
        "button_answer": "📞 Answer Call",
        "button_hangup": "🔴 Hang Up",
        "button_hold": "⏸️ Hold (Mute)",
        "button_resume": "▶️ Resume Call",
        "hold_status": "On Hold (Total Hold Time: {duration})",
        "cc_live_transcript": "🎤 Live CC Transcript",
        "mic_input_status": "🎙️ Agent Voice Input",
        "customer_audio_playback": "🗣️ Customer Audio Playback",
        "agent_response_prompt": "Record your response to the customer。",
        "agent_response_stop_and_send": "⏹️ Stop and share recording to customers",
        "call_end_message": "Call ended. Check AHT and history。",
        "call_query_placeholder": "Enter customer's initial query。",
        "call_number_placeholder": "+1 (555) 123-4567 (Mock Number)",
        "website_url_label": "Website URL (Optional)",
        "website_url_placeholder": "https://example.com (Enter website URL if available)",
        "call_summary_header": "AI Call Summary",
        "customer_audio_header": "Customer Initial Query (Voice)",
        "aht_not_recorded": "⚠️ Call start time not recorded。 Cannot calculate AHT。",
        "no_audio_record": "No initial customer voice record。",
        "customer_query_playing": "🔊 Playing customer inquiry...",
        "query_content_label": "📝 Inquiry content:",
        "auto_play_failed": "Auto-play failed: {error}. Please play manually.",
        "generating_customized_response": "Generating customized customer response...",
        "customer_responded": "🗣️ Customer responded: {reaction}",
        "customer_voice_generation_error": "❌ Customer voice generation error: {error}",
        "button_retry_translation": "Retry Translation",
        "customer_waiting_hold": "[Customer: Please wait...]",
        "agent_hold_message": "[Agent: Call is on hold. Please click the resume button.]",
        
        # --- Video File Upload Related ---
        "video_upload_expander": "Video File Upload/Load",
        "video_sync_enable": "Enable Video Synchronization (Play with TTS)",
        "video_rag_title": "🎥 OpenAI/Gemini Based Video RAG Feature",
        "video_rag_desc": "✅ **Current Implementation (Video RAG):**\n\n1. **LLM Text Analysis**: OpenAI/Gemini API analyzes customer's text to automatically determine emotional state and gestures.\n\n2. **Intelligent Video Selection**: Automatically selects appropriate video clips based on analysis results.\n   - Emotional State: HAPPY, ANGRY, ASKING, SAD, NEUTRAL\n   - Gestures: HAND_WAVE, NOD, SHAKE_HEAD, POINT, NONE\n\n3. **TTS Synchronized Playback**: Plays selected video and TTS-generated audio simultaneously.\n\n**Usage:**\n- Upload video files by gender (male/female) and emotional state.\n- Gesture-specific videos can also be uploaded (e.g., `male_happy_hand_wave.mp4`).\n- LLM automatically selects appropriate videos based on customer's speech content.",
        "video_gender_emotion_setting": "Video Settings by Gender and Emotional State",
        "video_gender_label": "Gender",
        "video_gender_male": "Male",
        "video_gender_female": "Female",
        "video_emotion_label": "Emotional State",
        "video_upload_label": "Video File Upload ({gender} - {emotion})",
        "video_current_selection": "📹 Current Selection: {gender} - {emotion}",
        "video_upload_prompt": "💡 Please upload the '{filename}' video file.",
        "video_save_path": "📂 Video Save Path:",
        "video_directory_empty": "⚠️ There is no file in the video directory. Please upload the file.",
        "video_directory_not_exist": "⚠️ Video directory does not exist: {path}",
        "video_local_path_input": "Or Enter Local File Path",
        "video_local_path_placeholder": "e.g., C:\\Users\\Admin\\Downloads\\video.mp4 or video.mp4",
        "video_current_avatar": "📺 Current Customer Avatar Video",
        "video_avatar_upload_prompt": "💡 Upload the '{filename}' video file to display the video.",
        "video_uploaded_files": "📁 Uploaded Video Files:",
        "video_bytes_saved": "✅ Video bytes saved: {name} ({size} MB)",
        "video_empty_error": "❌ Video file is empty. Please upload again.",
        "video_upload_error": "❌ Error occurred during video upload: {error}",
        "video_playback_error": "❌ Failed to play video.",
        "video_auto_play_info": "💡 This video will automatically play in '{gender} - {emotion}' state.",
        "video_preview_error": "Video preview error",
        "video_similar_gender": "Other videos of the same gender",
        "video_rename_hint": "💡 To use one of the videos above, rename the file or upload a new one.",
        "video_more_files": "... and {count} more",
        "avatar_status_info": "Status: {state} | Gender: {gender}",
        "customer_video_simulation": "Customer Video Simulation",
        "customer_avatar": "Customer Avatar",
        "faq_question_prefix": "Q{num}.",
        "visualization_chart": "Visualization Chart",
        "company_search_or_select": "Please search or select a company name.",

    },

    # --- ⭐ 일본어 버전 (한국어 100% 매칭) ---
    "ja": {
        "title": "パーソナライズAI学習コーチ (音声・ローカルDB)",
        "sidebar_title": "📚 AI学習コーチ設定",
        "file_uploader": "学習資料をアップロード (PDF, TXT, HTML)",
        "button_start_analysis": "資料分析開始 (RAGインデックス作成)",
        "rag_tab": "RAG知識チャットボット",
        "content_tab": "カスタム学習コンテンツ生成",
        "lstm_tab": "LSTM達成度予測ダッシュボード",
        "sim_tab_chat_email": "AI顧客対応シミュレーター(チャット・メール)",
        "sim_tab_phone": "AI顧客対応シミュレーター(電話)",
        "simulator_tab": "AI顧客対応シミュレーター",
        "company_info_tab": "会社情報およびFAQ",
        "sim_tab_chat_email_desc": "顧客対応業務において、チャットやメールで実際に問い合わせ対応ができる実戦向けの仮想シナリオです。AIが対応ガイドラインと草案を生成し、顧客の反応をシミュレートして実戦向けの訓練が可能です。",
        "sim_tab_phone_desc": "顧客対応業務において、電話で実際に問い合わせ対応ができる実戦向けの仮想シナリオです。音声録音およびリアルタイムCC字幕機能を提供し、電話通話シミュレーションを通じて実戦対応能力を向上させることができます。",
        "rag_tab_desc": "アップロードされた文書に基づいて質問に答える知識チャットボットです。PDF、TXT、HTMLファイルをアップロードしてRAG（Retrieval-Augmented Generation）インデックスを構築し、文書内容に基づいて正確な回答を提供します。",
        "content_tab_desc": "AIを活用して個人向けの学習コンテンツを生成する機能です。学習テーマと難易度に合わせて要点サマリー、選択式クイズ、実践例などを生成できます。",
        "lstm_tab_desc": "LSTMモデルを活用して学習者の達成度を予測し、ダッシュボードで可視化する機能です。過去のクイズスコアデータを分析して将来の達成度を予測し、学習成果を視覚的に確認できます。",
        "company_info_tab_desc": "会社別の詳細情報、人気商品、話題のニュース、FAQを検索・管理できる機能です。会社紹介、人気商品、話題のニュースを視覚化して一目で確認できます。",
        "voice_rec_header_desc": "音声録音および転写結果を管理・保存する機能です。マイクで録音するかファイルをアップロードしてWhisper APIを通じて音声をテキストに変換し、転写結果を保存・管理できます。",
        "more_features_label": "その他の機能",
        "rag_header": "RAG知識チャットボット (ドキュメントQ&A)",
        "rag_desc": "アップロードされた資料に基づいて質問に回答します。",
        "rag_input_placeholder": "資料について質問してください",
        "llm_error_key": "⚠️ 注意: GEMINI_API_KEY が設定されていません。",
        "llm_error_init": "LLM 初期化エラー：APIキーを確認してください。",
        "content_header": "カスタム学習コンテンツ生成",
        "content_desc": "学習テーマと難易度に応じてコンテンツを生成します。",
        "topic_label": "学習テーマ",
        "level_label": "難易度",
        "content_type_label": "コンテンツ種類",
        "level_options": ["初級", "中級", "上級"],
        "content_options": ["要点サマリー", "選択式クイズ10問", "実践例アイデア"],
        "button_generate": "生成する",
        "warning_topic": "学習テーマを入力してください。",
        "lstm_header": "LSTM達成度予測ダッシュボード",
        "lstm_desc": "仮想クイズスコアを使用して達成度を予測します。",
        "lang_select": "言語選択",
        "company_info_faq_settings": "会社別詳細情報とFAQ",
        "search_company": "会社名検索",
        "company_info": "会社情報",
        "company_faq": "よくある質問",
        "faq_question": "質問",
        "faq_answer": "回答",
        "popular_products": "人気商品",
        "trending_topics": "話題のニュース",
        "company_details": "会社詳細情報",
        "no_company_found": "に該当する会社が見つかりません。",
        "no_company_selected": "会社名を検索または選択してください。",
        "product_popularity": "商品人気度",
        "topic_trends": "話題トレンド",
        "select_company": "会社選択",
        "faq_search": "FAQ検索",
        "faq_search_placeholder": "FAQ検索語を入力してください",
        "faq_search_placeholder_extended": "FAQ検索語を入力してください（商品名、サービス名なども検索可能）",
        "button_search_faq": "検索",
        "company_search_placeholder": "例: サムスン、ネイバー、グーグル、アップルなど",
        "company_search_button": "検索",
        "generating_company_info": "会社情報を生成中...",
        "button_copy_answer": "回答コピー",
        "button_copy_hint": "ヒントコピー",
        "button_download_answer": "回答ダウンロード",
        "button_download_hint": "ヒントダウンロード",
        "copy_instruction": "💡 上のテキストを選択してCtrl+C（Mac: Cmd+C）でコピーしてください。",
        "copy_help_text": "テキストを選択してCtrl+C（またはCmd+C）でコピーしてください。",
        "button_reset": "リセット",
        "answer_displayed": "回答が表示されました。上のテキストをコピーしてください。",
        "hint_displayed": "ヒントが表示されました。上のテキストをコピーしてください。",
        "ai_answer_generated": "AI回答が生成されました。",
        "hint_generated": "対応ヒントが生成されました。",
        "warning_enter_inquiry": "顧客問い合わせ内容を入力してください。",
        "customer_inquiry_review_desc": "エージェントが上司に顧客問い合わせ内容を再確認し、AI回答とヒントを生成できる機能です。",
        "all_companies": "すべて",
        "optional": "任意",
        "no_faq_for_company": "{company}のFAQがありません。",
        "related_products": "関連商品",
        "related_trending_news": "関連話題のニュース",
        "related_company_info": "関連会社紹介内容",
        "related_faq": "関連FAQ",
        "items": "件",
        "popularity": "人気度",
        "no_faq_for_product": "該当商品に関連するFAQが見つかりません。商品情報のみ表示されます。",
        "generating_detail": "詳細内容を生成中...",
        "checking_additional_info": "詳細内容: {topic}に関する追加情報を確認中です。",
        "button_generate_faq": "FAQ生成",
        "button_add_company": "顧客問い合わせ再確認",
        "customer_inquiry_review": "顧客問い合わせ再確認",
        "inquiry_question_label": "顧客問い合わせ内容",
        "inquiry_question_placeholder": "顧客が問い合わせた内容を入力してください",
        "inquiry_attachment_label": "📎 顧客添付ファイルアップロード (写真/スクリーンショット)",
        "inquiry_attachment_help": "特にキャンセル不可の旅行商品で、飛行機の遅延、パスポートの問題などやむを得ない理由がある場合は、必ず写真やスクリーンショットを添付してください。",
        "inquiry_attachment_uploaded": "✅ 添付ファイルがアップロードされました: {filename}",
        "extracting_file_content": "ファイル内容を抽出中...",
        "detecting_language": "言語を検出中...",
        "translating_content": "ファイル内容を翻訳中...",
        "file_translated": "✅ ファイル内容が翻訳されました。",
        "file_extraction_error": "ファイル内容の抽出中にエラーが発生しました: {error}",
        "ocr_requires_manual": "画像OCRにはGemini APIキーが必要です。画像のテキストを手動で入力してください。",
        "ocr_error": "画像からのテキスト抽出中にエラーが発生しました: {error}",
        "button_generate_ai_answer": "AI回答生成",
        "button_generate_hint": "対応ヒント生成",
        "ai_answer_header": "AI推奨回答",
        "hint_header": "対応ヒント",
        "generating_ai_answer": "AI回答を生成中...",
        "generating_hint": "対応ヒントを生成中...",
        "button_edit_company": "会社情報編集",
        "button_show_company_info": "会社紹介を見る",
        "no_faq_results": "検索結果がありません。",
        "faq_search_results": "FAQ検索結果",
        "add_company_name": "会社名",
        "add_company_info": "会社情報",
        "generate_faq_question": "質問",
        "generate_faq_answer": "回答",
        "button_save_faq": "FAQ保存",
        "button_cancel": "キャンセル",
        "faq_saved_success": "FAQが保存されました。",
        "company_added_success": "会社が追加されました。",
        "company_updated_success": "会社情報が更新されました。",
        "interview_questions": "面接予想質問",
        "interview_questions_desc": "面接で出る可能性のある核心的な質問と詳細な回答です。面接準備と会社理解に役立ちます。",
        "interview_category_other": "その他",
        "ceo_info": "CEO/代表取締役情報",
        "position": "役職",
        "tenure": "在任期間",
        "ceo_bio": "紹介",
        "education": "学歴",
        "career": "主要な経歴",
        "embed_success": "{count}個のチャンクでDB構築完了!",
        "embed_fail": "埋め込み失敗：クォータ超過またはネットワーク問題。",
        "warning_no_files": "資料をアップロードしてください。",
        "warning_rag_not_ready": "RAGが準備できていません。",
        "quiz_fail_structure": "クイズデータの形式が正しくありません。",
        "select_answer": "回答を選択してください",
        "check_answer": "回答を確認",
        "next_question": "次の質問",
        "correct_answer": "正解！ 🎉",
        "incorrect_answer": "不正解 😞",
        "correct_is": "正解",
        "explanation": "解説",
        "quiz_complete": "クイズ完了!",
        "score": "スコア",
        "retake_quiz": "再挑戦",
        "question_label": "質問",
        "correct_questions": "正解",
        "incorrect_questions": "不正解",
        "question_result": "問題結果",
        "your_answer": "あなたの答え",
        "correct_answer_label": "正解",
        "quiz_error_llm": "퀴즈 생성 실패：JSON形式が正しくありません。",
        "quiz_original_response": "LLM 原本回答",
        "firestore_loading": "RAGインデックス読み込み中...",
        "firestore_no_index": "保存されたRAGインデックスが見つかりません。",
        "db_save_complete": "(DB保存完了)",
        "data_analysis_progress": "資料分析中...",
        "response_generating": "応答生成中...",
        "lstm_result_header": "達成度予測結果",
        "lstm_score_metric": "予測達成度",
        "lstm_score_info": "次のスコア予測: **{predicted_score:.1f}점**",
        "lstm_rerun_button": "新しいデータで再予測",

        # --- 토스트 메시지 추가 ---
        "toast_like": "🔥 コンテンツを気に入っていただけました！ (+1 カウント反映)",
        "toast_dislike": "😔 より良いコンテンツのためフィードバックを記録しました。",
        "toast_share": "🌐 コンテンツリンクが生成されました。",
        "toast_copy": "✅ コンテンツがクリップボードにコピーされました！",
        "toast_more": "ℹ️ その他のオプション（印刷、PDF保存など）",
        "mock_pdf_save": "📥 PDFで保存",
        "mock_word_open": "📑 Wordで開く",
        "mock_print": "🖨 印刷",
        # --- 토스트 메시지 끝 ---

        # --- Simulator ---
        "simulator_header": "AI顧客対応シミュレーター",
        "simulator_desc": "難しい顧客問い合わせに対するAIのガイドラインと草案を生成します。",
        "customer_query_label": "顧客からの問い合わせ内容 (リンク可)",
        "customer_type_label": "顧客タイプ",
        "customer_type_options": ["一般的な問い合わせ", "難しい顧客", "非常に不満な顧客"],
        "button_simulate": "応対ガイド生成",
        "customer_generate_response_button": "顧客の返信を生成",
        "send_closing_confirm_button": "追加のご質問有無を確認するメッセージを送信",
        "simulation_warning_query": "お問い合わせ内容を入力してください。",
        "simulation_no_key_warning": "⚠️ APIキー不足のため応対生成不可。",
        "simulation_advice_header": "AI対応ガイドライン",
        "simulation_draft_header": "推奨応対草案",
        "button_listen_audio": "音声で聞く",
        "tts_status_ready": "音声生成準備完了",
        "tts_status_generating": "音声生成中...",
        "tts_status_success": "音声準備完了！",
        "tts_status_error": "TTS エラーが発生しました",
        "history_expander_title": "📝 過去の対応履歴を読み込む (最新10件)",
        "initial_query_sample": "パリに到着しましたが、KlookのeSIMが使えません…",
        "button_mic_input": "🎙 音声入力",
        "button_mic_stop": "⏹️ 録音終了",
        "prompt_customer_end": "追加の質問がないためチャットを終了します。",
        "prompt_survey": "担当エージェント000でした。良い一日をお過ごしください。 [アンケートリンク]",
        "customer_closing_confirm": "他のお問合せはございませんでしょうか。",
        "customer_positive_response": "承知いたしました。ありがとうございます。",
        "button_email_end_chat": "応対終了（アンケート）",
        "error_mandatory_contact": "メールアドレスと電話番号の入力は必須です。",
        "customer_attachment_label": "📎 顧客添付ファイルアップロード",
        "attachment_info_llm": "[顧客添付ファイル: {filename}が確認されました。このファイルを参照して対応してください。]",
        "button_retry_translation": "翻訳を再試行",
        "button_request_hint": "💡 応対ヒントを要請 (AHT モニタリング中)",
        "button_generate_draft": "🤖 AI応答草案生成",
        "draft_generating": "AIが応答草案を生成中です...",
        "draft_success": "✅ AI応答草案が生成されました。以下で確認して修正してください。",
        "hint_placeholder": "お問合せの応対に対するヒント：",
        "new_simulation_ready": "新しいシミュレーションを開始できます。",
        "survey_sent_confirm": "📨 アンケートリンクを送信しました。このチャットは終了しました。",
        "agent_response_header": "✍️ エージェント応答",
        "agent_response_placeholder": "顧客へ返信内容を入力…",
        "generating_customer_response": "顧客の返信を生成中...",
        "call_started_message": "通話が開始されました。下のマイクボタンをクリックして挨拶を録音してください。",
        "call_on_hold_message": "通話が保留中です。通話を再開した後、録音が可能です。",
        "recording_complete_transcribing": "🎙️ 録音完了。転写処理中...",
        "recording_complete_press_transcribe": "✅ 録音完了！以下の転写ボタンを押してテキストに変換してください。",
        "customer_positive_solution_reaction": "お客様がソリューションに肯定的に反応しました。追加の問い合わせの有無を確認してください。",
        "transcription_empty_warning": "⚠️ 転写結果が空です。もう一度録音してください。（マイク入力がないか、ミュートされています）",
        "transcription_error": "[ERROR: 転写失敗]",
        "transcription_no_result": "❌ 転写結果がありません。",
        "send_response_button": "返信送信",
        "customer_turn_info": "エージェント応答送信完了。顧客の反応を自動生成中です。",
        "generating_customer_response": "顧客の反応を生成中...",
        "customer_escalation_start": "上級の担当者と話したい",
        "request_rebuttal_button": "顧客の反応を生成",
        "new_simulation_button": "新規シミュレーション",
        "history_selectbox_label": "履歴を選択:",
        "history_load_button": "履歴を読み込む",
        "delete_history_button": "❌ 全履歴削除",
        "delete_confirm_message": "すべての履歴を削除しますか？",
        "delete_confirm_yes": "はい、削除します。",
        "download_history_word": "📥 履歴ダウンロード (Word)",
        "download_history_pptx": "📥 履歴ダウンロード (PPTX)",
        "download_history_pdf": "📥 履歴ダウンロード (PDF)",
        "download_current_session": "📥 現在のセッションをダウンロード",
        "delete_confirm_no": "いいえ、維持します。",
        "delete_success": "削除完了！",
        "deleting_history_progress": "削除中...",
        "search_history_label": "履歴検索",
        "date_range_label": "日付フィルター",
        "history_search_button": "🔍 検索",
        "no_history_found": "該当する履歴はありません。",
        "customer_email_label": "顧客メールアドレス（必修）",
        "customer_phone_label": "顧客連絡先 / 電話番号（必修）",
        "transfer_header": "言語切り替え要請（他チームへ）",
        "transfer_to_en": "🇺🇸 英語チームへ転送",
        "transfer_to_ja": "🇯🇵 日本語チームへ転送",
        "transfer_to_ko": "🇰🇷 韓国語チームへ転送",
        "transfer_system_msg": "📌 システムメッセージ: 顧客の要請により、対応言語が {target_lang} チームへ切り替えられました。新しい担当者(AI)が対応します。",
        "transfer_loading": "転送中: 過去のチャット履歴を翻訳およびレビューしています (お客様には3〜10分のお時間をいただいています)",
        "transfer_summary_header": "🔍 転送された担当者向けの要約 (翻訳済み)",
        "transfer_summary_intro": "これが顧客との過去のチャット履歴です。この要約に基づいてサポートを続けてください。",
        "llm_translation_error": "❌ 翻訳失敗: LLM応答エラー",
        "timer_metric": "経過時間",
        "timer_info_ok": "AHT (15分基準)",
        "timer_info_warn": "AHT (10分経過)",
        "timer_info_risk": "🚨 15分経過: 高いリスク",
        "solution_check_label": "✅ この応答に解決策/対応策が含まれています。",
        "sentiment_score_label": "顧客の感情スコア",  # <--- 추가/수정
        "urgency_score_label": "緊急度スコア",
        "customer_gender_label": "顧客性別",
        "customer_emotion_label": "顧客感情状態",
        "gender_male": "男性",
        "gender_female": "女性",
        "emotion_happy": "気分良い顧客",
        "emotion_dissatisfied": "不満な顧客",
        "emotion_angry": "怒った顧客",
        "emotion_sad": "悲しい/憂鬱な顧客",
        "emotion_neutral": "中立",
        "similarity_chart_title": "類似性ケースの比率",
        "scores_comparison_title": "感情及び満足度のスコア",
        "similarity_score_label": "類似性",
        "satisfaction_score_label": "満足度",
        "customer_satisfaction_score_label": "顧客満足度スコア",
        "sentiment_trend_label": "感情のスコアの推測",
        "satisfaction_trend_label": "満足度のスコアの推測",
        "case_trends_title": "過去に推定されたスコア",
        "date_label": "日付",
        "score_label": "スコア (0-100)",
        "customer_characteristics_title": "顧客の性格",
        "language_label": "言語",
        "email_provided_label": "提供されたメールアドレス",
        "phone_provided_label": "提供された電話番号",
        "region_label": "地域",
        "btn_request_phone_summary": "履歴を要約する",
        
        # --- 다운로드 문서 관련 텍스트 ---
        "download_history_title": "顧客対応履歴要約",
        "download_history_number": "履歴 #",
        "download_initial_inquiry": "初期問い合わせ",
        "download_summary": "要約",
        "download_main_inquiry": "主な問い合わせ",
        "download_key_response": "核心応答",
        "download_customer_characteristics": "顧客特性",
        "download_privacy_summary": "個人情報要約",
        "download_address_provided": "住所提供",
        "download_overall_summary": "全体要約",
        "download_yes": "はい",
        "download_no": "いいえ",
        "download_created_date": "作成日",
        "download_cultural_background": "文化的背景",
        "download_communication_style": "コミュニケーションスタイル",
        "download_region_hint": "地域ヒント",

        # --- 추가된 전화 발신 기능 관련 ---
        "button_call_outbound": "電話発信",
        "button_call_outbound_to_customer": "顧客へ電話発信",
        "button_call_outbound_to_provider": "現地業者へ電話発信",
        "call_outbound_system_msg": "📌 システムメッセージ: エージェントが{target}へ電話発信を試みました。",
        "call_outbound_simulation_header": "📞 電話発信シミュレーション結果",
        "call_outbound_summary_header": "📞 現地業者/顧客との通話要約",
        "call_outbound_loading": "電話接続と通話結果の整理中... (LLMコール)",
        "call_target_select_label": "発信先選択",
        "call_target_customer": "顧客へ電話発信",
        "call_target_partner": "現地業者へ電話発信",

        # --- Voice ---
        "voice_rec_header": "音声記録＆管理",
        "record_help": "録音するか音声ファイルをアップロードします。",
        "uploaded_file": "音声ファイルをアップロード",
        "rec_list_title": "保存された音声記録",
        "transcribe_btn": "転写 (Whisper)",
        "save_btn": "音声記録を保存",
        "transcribing": "音声を転写中...",
        "transcript_result": "転写結果:",
        "transcript_text": "転写テキスト",
        "openai_missing": "OpenAI APIキーがありません。",
        "whisper_client_error": "❌ エラー: Whisper APIクライアントが初期化されていません。",
        "whisper_auth_error": "❌ Whisper API認証に失敗しました。",
        "whisper_format_error": "❌ エラー: この音声形式はサポートされていません。",
        "whisper_success": "✅ 音声転写完了！",
        "playback": "録音再生",
        "retranscribe": "再転写",
        "delete": "削除",
        "no_records": "保存された音声記録はありません。",
        "saved_success": "保存しました！",
        "delete_confirm_rec": "この音声記録を削除しますか？",
        "gcs_not_conf": "GCSが設定されていないか、音声がありません。",
        "gcs_playback_fail": "音声の再生に失敗しました。",
        "gcs_no_audio": "音声ファイルがありません。",
        "error": "エラー:",
        "firestore_no_db_connect": "DB接続失敗",
        "save_history_success": "保存完了。",
        "save_history_fail": "保存失敗。",
        "delete_fail": "削除失敗",
        "rec_header": "音声入力＆転写",
        "whisper_processing": "処理中...",
        "empty_response_warning": "応答を入力してください。",
        "customer_no_more_inquiries": "いいえ、結構です。大丈夫です。有難う御座いました。",
        "customer_has_additional_inquiries": "はい、追加の問い合わせがあります。",
        "sim_end_chat_button": "アンケートリンクを送信して応対終了",
        "delete_mic_record": "録音を削除する",
        "agent_confirmed_additional_inquiry": "エージェントが追加の問い合わせの有無を確認しました。お客様の最終回答を自動生成します。",
        "llm_key_missing_customer_response": "LLMキーがないため、顧客の反応を自動生成できません。手動で「顧客の返信を生成」ボタンをクリックするか、AGENT_TURNに戻ってください。",
        "customer_response_generation_failed": "顧客の応答を生成できませんでした。もう一度お試しください。",
        "no_more_inquiries_confirmed": "✅ お客様に追加の問い合わせがないことを確認しました。",
        "consultation_end_header": "📋 相談終了",
        "click_survey_button_to_end": "以下の**アンケートリンクを送信して応対終了**ボタンをクリックして相談を終了してください。",

        # --- 첨부 파일 기능 추가 ---
        "attachment_label": "顧客の添付ファイルアップロード (スクリーンショットなど)",
        "attachment_placeholder": "ファイルを添付して状況を説明してください（オプション）",
        "attachment_status_llm": "顧客が **{filename}** 파일을 첨부했습니다. 이 파일을 스크린샷이라고 가정하고 응대 초안과 가이드라인에 반영해주세요. (ファイルタイプ: {filetype})",
        "agent_attachment_label": "エージェント添付ファイル (スクリーンショットなど)",
        "agent_attachment_placeholder": "応答に添付するファイルを選択してください（オプション）",
        "agent_attachment_status": "📎 エージェントが **{filename}** ファイルを応答に添付しました。(ファイルタイプ: {filetype})",

        # --- RAG 오류 메시지 추가 ---
        "rag_embed_error_openai": "RAG embedding failed: OpenAI API Key is invalid or not set。",
        "rag_embed_error_gemini": "RAG embedding failed: Gemini API Key is invalid or not set。",
        "rag_embed_error_nvidia": "RAG embedding failed: NVIDIA API Key is invalid or not set。",
        "rag_embed_error_none": "RAG embedding failed: All required keys (OpenAI, Gemini, NVIDIA) are invalid or not set。 Please configure a key。",

        # --- 電話機能関連追加 ---
        "phone_header": "AI顧客対応シミュレーター(電話)",
        "call_status_waiting": "着信待ち...",
        "call_status_ringing": "着信中: {number}",
        "button_answer": "📞 電話に出る",
        "button_hangup": "🔴 電話を切る",
        "button_hold": "⏸️ 保留 (ノイズ遮断)",
        "button_resume": "▶️ 通話再開",
        "hold_status": "保留中 (累計保留時間: {duration})",
        "cc_live_transcript": "🎤 リアルタイムCC字幕 / 転写",
        "mic_input_status": "🎙️ エージェントの音声入力",
        "customer_audio_playback": "🗣️ 顧客の音声再生",
        "agent_response_prompt": "顧客への応答を録音してください。",
        "agent_response_stop_and_send": "⏹️録音を終了して、顧客へ転送する",
        "call_end_message": "通話が終了しました。AHTと履歴を確認してください。",
        "call_query_placeholder": "顧客からの最初の問い合わせ内容を入力してください。",
        "call_number_placeholder": "+81 90-xxxx-xxxx (仮想番号)",
        "website_url_label": "ホームページのウェブアドレス (任意)",
        "website_url_placeholder": "https://example.com (ホームページのアドレスがある場合は入力してください)",
        "call_summary_header": "AI 通話要約",
        "customer_audio_header": "顧客の最初の問い合わせ (音声)",
        "aht_not_recorded": "⚠️ 通話開始時間が記録されていないため、AHTを計算できません。",
        "no_audio_record": "顧客の最初の音声記録はありません。",
        "customer_query_playing": "🔊 顧客の問い合わせを再生中です。",
        "query_content_label": "📝 問い合わせ内容:",
        "auto_play_failed": "自動再生に失敗しました: {error}。手動で再生してください。",
        "generating_customized_response": "顧客向けカスタマイズされた反応を生成中...",
        "customer_responded": "🗣️ 顧客が応答しました: {reaction}",
        "customer_voice_generation_error": "❌ 顧客の音声生成エラー: {error}",
        "button_retry_translation": "翻訳を再試行",
        "customer_waiting_hold": "[顧客: お待ちください...]",
        "agent_hold_message": "[エージェント: 通話が保留中です。通話再開ボタンをクリックしてください。]",
        
        # --- ビデオファイルアップロード関連 ---
        "video_upload_expander": "ビデオファイルアップロード/ロード",
        "video_sync_enable": "ビデオ同期を有効化 (TTSと一緒に再生)",
        "video_rag_title": "🎥 OpenAI/GeminiベースのビデオRAG機能",
        "video_rag_desc": "✅ **現在の実装方式 (ビデオRAG):**\n\n1. **LLMテキスト分析**: OpenAI/Gemini APIが顧客のテキストを分析し、感情状態とジェスチャーを自動判定します。\n\n2. **インテリジェントビデオ選択**: 分析結果に基づいて適切なビデオクリップを自動選択します。\n   - 感情状態: HAPPY, ANGRY, ASKING, SAD, NEUTRAL\n   - ジェスチャー: HAND_WAVE, NOD, SHAKE_HEAD, POINT, NONE\n\n3. **TTS同期再生**: 選択されたビデオとTTSで生成された音声を同時に再生します。\n\n**使用方法:**\n- 性別(男性/女性)と感情状態別にビデオファイルをアップロードしてください。\n- ジェスチャー別のビデオもアップロード可能です (例: `male_happy_hand_wave.mp4`)。\n- 顧客が話す内容に応じてLLMが自動的に適切なビデオを選択します。",
        "video_gender_emotion_setting": "性別および感情状態別ビデオ設定",
        "video_gender_label": "性別",
        "video_gender_male": "男性",
        "video_gender_female": "女性",
        "video_emotion_label": "感情状態",
        "video_upload_label": "ビデオファイルアップロード ({gender} - {emotion})",
        "video_current_selection": "📹 現在の選択: {gender} - {emotion}",
        "video_upload_prompt": "💡 '{filename}' ビデオファイルをアップロードしてください。",
        "video_save_path": "📂 ビデオ保存パス:",
        "video_directory_empty": "⚠️ ビデオディレクトリにファイルがありません。ファイルをアップロードしてください。",
        "video_directory_not_exist": "⚠️ ビデオディレクトリが存在しません: {path}",
        "video_local_path_input": "またはローカルファイルパス入力",
        "video_local_path_placeholder": "例: C:\\Users\\Admin\\Downloads\\video.mp4 または video.mp4",
        "video_current_avatar": "📺 現在の顧客アバター映像",
        "video_avatar_upload_prompt": "💡 '{filename}' ビデオファイルをアップロードすると映像が表示されます。",
        "video_uploaded_files": "📁 アップロードされたビデオファイル:",
        "video_bytes_saved": "✅ ビデオバイト保存完了: {name} ({size} MB)",
        "video_empty_error": "❌ ビデオファイルが空です。再度アップロードしてください。",
        "video_upload_error": "❌ ビデオアップロード中にエラーが発生しました: {error}",
        "video_playback_error": "❌ ビデオ再生に失敗しました。",
        "video_auto_play_info": "💡 このビデオは '{gender} - {emotion}' 状態で自動的に再生されます。",
        "video_preview_error": "ビデオプレビューエラー",
        "video_similar_gender": "同じ性別の他のビデオ",
        "video_rename_hint": "💡 上記のビデオのいずれかを使用するには、ファイル名を変更するか、新しくアップロードしてください。",
        "video_more_files": "... 他 {count}件",
        "avatar_status_info": "状態: {state} | 性別: {gender}",
        "customer_video_simulation": "顧客映像シミュレーション",
        "customer_avatar": "顧客アバター",
        "faq_question_prefix": "Q{num}.",
        "visualization_chart": "可視化チャート",
        "company_search_or_select": "会社名を検索または選択してください。",
    }
}
